### PR TITLE
NEW Add behat tests for using compare mode

### PR DESCRIPTION
**Pull request by robbieaverill**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Yep, they need to be updated now

**Comment by robbieaverill** [comment]
Updating them now

**Comment by robbieaverill** [comment]
Updated

**Comment by raissanorth** [comment]
Awesome, let's merge on green.

**Comment by robbieaverill** [comment]
It was green, someone merged a PR without dist files built which is why its red now in one of the two builds

**Pull request merged**
