### PR TITLE
Add tests for HistoryViewerVersion

### PR DESCRIPTION
**Pull request by raissanorth**
And bump the code coverage 😏 

Also changes the PropType for the compareType - something that the tests picked up.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Are the behat failures related?

**Comment by raissanorth** [comment]
@robbieaverill Could well be, since the HistoryViewerVersion itself is not clickable any longer, but rather the `<a>` nested inside it. I will investigate and see if I can fix them.

**Comment by raissanorth** [comment]
Actually, I reckon the Behat tests might be affected by 30d331c6d4739215d6c18b81e990d549740814e0, since we used the markup to find all versions. They are however list items now instead of table rows.

**Comment by robbieaverill** [comment]
Interesting they didn’t fail when that was merged. Would you mind updating the feature context class to find the anchor instead?

**Comment by raissanorth** [comment]
@robbie Working on it atm.

**Comment by raissanorth** [comment]
I still encounter some local failures, but they are not consistent, so I am curious to see what the result of the Travis' tests is.

**Comment by raissanorth** [comment]
💚

**Pull request merged**
